# Generated by Django 5.0.6 on 2024-07-09 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Choice',
        ),
    ]
